### ISSUE TITLE
Host your own Flatpak repo

### ISSUE THREAD

**Issue by LeandroStanger** [fastrizwaan/flatpak-wine#1]

**Comment by fastrizwaan** [comment]
flatpak-wine32 is wine 6.0 with 32 bit support. Whereas this one is WoW64, we can install both 32 and 64 bit games. I played Bloody Spell with this, needs wintricks corefonts for text to work

https://github.com/fastrizwaan/flatpak-wine32/blob/main/io.github.Proton-6.1-GE-2-wine.yml (builds in 5 minutes) but size of flatpak is is 220+MB (due to 800+MB Proton wine directory)

`flatpak run io.github.Proton-61-GE-2  BloodySpell.exe`
![Screenshot from 2021-03-11 18-32-40](https://user-images.githubusercontent.com/1161682/110791497-4b9aad00-8298-11eb-8275-f82f0c007c4f.png)

Lutris does not load this game.

So, I'm thinking of making providing Proton flatpak. I don't know much about hosting repo. Need to learn about that.

**Comment by LeandroStanger** [comment]
```
I don't know much about hosting repo
```
https://docs.flatpak.org/en/latest/hosting-a-repository.html#hosting-a-repository

**Comment by fastrizwaan** [comment]
Just created flatpak-wine64 (don't know how to build wow64 using flatpak-builder)
https://github.com/fastrizwaan/flatpak-wine64
```
flatpak run --command=winetricks io.github.flatpak-wine64  corefonts
flatpak run io.github.flatpak-wine64  Bloody*.exe
```
Game runs!

**Comment by fastrizwaan** [comment]
will try to get winezgui in flathub.
