### ISSUE TITLE
How to add the icon to the Desktop?

### ISSUE THREAD

**Issue by LeandroStanger** [fastrizwaan/flatpak-wine#4]

**Comment by fastrizwaan** [comment]
Downlaod npp installer ( https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.9.3/npp.7.9.3.Installer.exe) in a prefix say .npp

#### Install into ~/.npp wineprefix or bottle
`WINEPREFIX=~/.npp flatpak run io.github.flatpak-wine32 ~/Downloads/npp.7.9.3.Installer.exe`

##### The .desktop file is created here:
`~/.var/app/io.github.flatpak-wine32/data/applications/wine/Programs/Notepad++/Notepad++.desktop`

### To Add the Icon to Desktop (Answer to your question)

##### copy the desktop file
copy to exports directory which gives access to wine's desktop/shortcut file
`cp ~/.var/app/io.github.flatpak-wine32/data/applications/wine/Programs/Notepad++.desktop ~/.local/share/flatpak/exports/share/applications/`

##### replace wine with flatpak run io.github.flatpak-win32 from the desktop file
`sed 's/ wine C/ flatpak run io.github.flatpak-wine32 C/g' -i ~/.local/share/flatpak/exports/share/applications/Notepad++.desktop`

#### we give Absolute path of icon so that Notepadd++ shows the icon
##### Icon=XXX to Icon=~/.var/..../XXX.png
`sed "s|Icon=\(.*\)|Icon=$HOME/.var/app/io.github.flatpak-wine32/data/icons/hicolor/128x128/apps/\1.png|" -i ~/.local/share/flatpak/exports/share/applications/Notepad++.desktop`


##### Copying icon to export's icon directory not working
`cp  ~/.var/app/io.github.flatpak-wine32/data/icons/hicolor/128x128/apps/33E8_notepad++.0.png ~/.local/share/flatpak/exports/share/icons/hicolor/128x128/apps/`

**Comment by fastrizwaan** [comment]
Hi, you can rightclick and create desktop shortcut now!

**Comment by fastrizwaan** [comment]
Right-Click and option comes to create shortcut (bottle). flatpak wine 5.0.5
https://github.com/fastrizwaan/flatpak-wine-releases/releases

will improve this even more.

**Comment by fastrizwaan** [comment]
using this to get newly installed app shortucts created from installer.

**Comment by fastrizwaan** [comment]
the wine inside flatpak is sandboxed, I'm working on installer support in WineZGUI, the installer branch works though.

**Comment by fastrizwaan** [comment]
flatpak-wine 0.88+ (WineZGUI-0.88+) supports installers and creates desktop shortcuts as expected.
