### ISSUE TITLE
[Feature Request] That when you create a prefix,that it will have all the needed additional software.

### ISSUE THREAD

**Issue by ghost** [fastrizwaan/flatpak-wine#8]
Example:You have a game that needs dxvk,xinput,vcrun and corefonts,then you would need to create a prefix and then install that additional software manually and when there is an update for the additional software (for example there is a new dxvk version or new vcrun) and the game needs that to run better,then you would also need to update that manually.
So what I want is that when you create a prefix that it automatically has dxvk,xinput,vcrun,corefonts and mono installed,cause many games need those anyway.
And when there is a new dxvk version or new vcrun that then that gets automatically updated/added.
And another thing,it would be faster if flatpak wine would have a template prefix and every time you choose the "create new prefix" option,that then flatpak wine copy and pastes that template prefix to the location you want to create the prefix instead of creating an entirely new prefix,cause pasting is much faster.

**Comment by fastrizwaan** [comment]
Looks like you want default wineprefix+ dxvk corefonts, dotnet48 etc. instead of vanilla .wine! You could install once, and copy that .wine directory and reuse that .wine+dxvk copy for new games. say you need to install GAME1 and GAME2, both needs say corefonts and dxvk.

### WINE WITH DEPENDENCIES
##### 1st create your "required" wine with dependencies
`WINEPREFIX=~/.MYWINE winetricks --force --unattended corefonts dxvk`

##### for GAME1
```
cp ~/.MYWINE ~/.GAME1 -rv ; #copy 
WINEPREFIX=~/.GAME1 wine GAME1/SETUP.exe
```
##### for GAME2
```
cp ~/.MYWINE ~/.GAME2 -rv ; #copy 
WINEPREFIX=~/.GAME2 wine GAME2/SETUP.exe
```

Now, coming to automatic update, it is you, who have to download latest winetricks or git clone dxvk then run install with the WINEPREFIX=; or you have to run a daemon which looks up for new releases and automatically update. There is high probability that updates may break your game.

flatpak-wine keeps setup files say vcrun, dxvk etc. in cache, whenever you are installing again, it takes only minutes to install from the cache (as no download is repeated).

Once you've setup you game properly, you don't need to update unless you are having some bugs or issues.

 flatpak-wine installs with `winetricks --force --unattended dxvk corefonts faudio quartz dotnet48`  ; so you don't have to manually click next, next finish. it's unattended install. so just have some snack while it installs.

**Comment by fastrizwaan** [comment]
Done. flatpak-wine 0.88+ (WineZGUI-0.88+) supports Prefix Templates. Thanks.
